#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : Students' Mental Health  # The title of the book. Will be placed in the left navbar.
author                      : Hoa Tran  # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer

#######################################################################################
# Advanced and power-user settings
sphinx:
  recursive_update          : true # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js