title: 'Students' Mental Health'
author: Hoa Tran
# logo: content/images/econ-models.png
copyright: '2024'

execute:
  execute_notebooks: off

html:
  navbar_number_sections: true

sphinx:
  recursive_update: true
  config:
    html_js_files:
      - "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"
